name: Python application

on: [push]

env:
  POETRY_VERSION: 1.0.0
  WORK_DIR: ./punctuator


jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up cache
      uses: actions/cache@v1
      with:
        path: ./punctuator/.venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.PYTHON_VERSION }}
        poetry_version: ${{ env.POETRY_VERSION }}
        working_directory: ${{ env.WORK_DIR }}
        args: install

    - name: Lint with flake8
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.PYTHON_VERSION }}
        poetry_version: ${{ env.POETRY_VERSION }}
        working_directory: ${{ env.WORK_DIR }}
        args: run lint

    - name: Formatter
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.PYTHON_VERSION }}
        poetry_version: ${{ env.POETRY_VERSION }}
        working_directory: ${{ env.WORK_DIR }}
        args: run foramt-check

    - name: Import optimization
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.PYTHON_VERSION }}
        poetry_version: ${{ env.POETRY_VERSION }}
        working_directory: ${{ env.WORK_DIR }}
        args: run import-check

