name: Python application

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up cache
      uses: actions/cache@v1
      with:
        path: ./punctuator/.venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.5
        poetry_version: 1.0.0
        working_directory: ./punctuator # Optional, defaults to '.'
        args: install

    - name: Lint with flake8
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.5
        poetry_version: 1.0.0
        working_directory: ./punctuator
        args: run lint

    - name: Formatter
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.5
        poetry_version: 1.0.0
        working_directory: ./punctuator
        args: run foramt-check

    - name: Import optimization
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.5
        poetry_version: 1.0.0
        working_directory: ./punctuator
        args: run import-check

