name: Python application

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.5
        poetry_version: 1.0.0
        working_directory: ./punctuator # Optional, defaults to '.'
        args: install

    - name: Set up cache
      uses: actions/cache@v1
      working-directory: ./punctuator
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Lint with flake8
      run: |
        poetry add --dev flake8
        flake8 punctuator --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Formatter
      run: |
        poetry add --dev yapf
        yapf -r -d --style pep8 punctuator

    - name: Import optimization
      run: |
        poetry add --dev isort
        isort -rc -d -c punctuator

